
Beginning at: 2018-07-31 12:17:20.127555
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 12:23:45.905121
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 12:31:13.872117
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 12:45:00.889072
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 15:52:42.893219
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 15:54:51.447884
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.
GET http://elasticsearch:9200/wiki/page/_search [status:N/A request:0.030s]
Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 171, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1058c8e48>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
GET http://elasticsearch:9200/wiki/page/_search [status:N/A request:0.005s]
Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 171, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x1058f9208>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
GET http://elasticsearch:9200/wiki/page/_search [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 171, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x105924ac8>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
GET http://elasticsearch:9200/wiki/page/_search [status:N/A request:0.022s]
Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/connection.py", line 56, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 171, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x105924be0>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known
127.0.0.1 [31/Jul/2018:12:54:53 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 557 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Server shutting down.

Beginning at: 2018-07-31 15:55:08.241995
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.
GET http://localhost:9200/wiki/page/_search [status:404 request:0.412s]
127.0.0.1 [31/Jul/2018:12:55:10 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
127.0.0.1 [31/Jul/2018:12:55:11 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://0.0.0.0:5000/?index=wiki&doc_type=page&search=%22Australia%22" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.013s]
127.0.0.1 [31/Jul/2018:12:55:12 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.014s]
127.0.0.1 [31/Jul/2018:12:55:13 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.004s]
127.0.0.1 [31/Jul/2018:12:55:13 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.005s]
127.0.0.1 [31/Jul/2018:12:55:14 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.008s]
127.0.0.1 [31/Jul/2018:12:55:15 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.005s]
127.0.0.1 [31/Jul/2018:12:55:16 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.007s]
127.0.0.1 [31/Jul/2018:12:55:17 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.008s]
127.0.0.1 [31/Jul/2018:12:55:18 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.022s]
127.0.0.1 [31/Jul/2018:12:55:18 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.021s]
127.0.0.1 [31/Jul/2018:12:55:19 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.010s]
127.0.0.1 [31/Jul/2018:12:55:20 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.005s]
127.0.0.1 [31/Jul/2018:12:55:20 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.034s]
127.0.0.1 [31/Jul/2018:12:55:21 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
GET http://localhost:9200/wiki/page/_search [status:404 request:0.013s]
127.0.0.1 [31/Jul/2018:12:55:22 +0000] "GET /?index=wiki&doc_type=page&search=%22Australia%22 HTTP/1.1" 500 271 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Server shutting down.

Beginning at: 2018-07-31 13:07:59.978236
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 13:10:07.193821
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 16:12:44.274281
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.
127.0.0.1 [31/Jul/2018:13:12:46 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
127.0.0.1 [31/Jul/2018:13:12:47 +0000] "GET /favicon.ico HTTP/1.1" 404 172 "http://127.0.0.1:5000/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Server shutting down.
Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() running at /Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py:361> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10f346078>()]>>

Beginning at: 2018-07-31 13:15:44.046767
Serving on ('127.0.0.1', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 13:28:50.701128

Beginning at: 2018-07-31 13:29:59.936367

Beginning at: 2018-07-31 13:31:09.035855

Beginning at: 2018-07-31 13:33:37.541623
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.
192.168.80.1 [31/Jul/2018:13:33:51 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
192.168.80.1 [31/Jul/2018:13:51:10 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Beginning at: 2018-07-31 18:10:13.074875

Beginning at: 2018-07-31 18:10:52.699272

Beginning at: 2018-07-31 18:11:40.982380
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Beginning at: 2018-07-31 18:11:59.257746

Beginning at: 2018-07-31 18:12:42.899196

Beginning at: 2018-07-31 18:13:05.264138

Beginning at: 2018-07-31 18:13:24.297996

Beginning at: 2018-07-31 18:13:32.108629

Server shutting down.

Beginning at: 2018-07-31 18:13:41.063395
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.
127.0.0.1 [31/Jul/2018:15:13:47 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
127.0.0.1 [31/Jul/2018:15:13:49 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Server shutting down.
Task was destroyed but it is pending!
task: <Task pending coro=<RequestHandler.start() done, defined at /Users/nikitagold/Documents/Projects/Dockers/elastic/rest_api/venv/lib/python3.6/site-packages/aiohttp/web_protocol.py:342> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x1065a61c8>()]>>

Beginning at: 2018-07-31 18:14:04.805785

Beginning at: 2018-07-31 18:14:24.723872

Beginning at: 2018-07-31 18:14:59.439306

Beginning at: 2018-07-31 18:15:46.283326

Beginning at: 2018-07-31 18:16:22.725448

Beginning at: 2018-07-31 18:16:39.007830

Beginning at: 2018-07-31 18:16:47.761782

Beginning at: 2018-07-31 18:19:04.212822
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:19:24.921221

Beginning at: 2018-07-31 18:20:09.282126
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:20:21.174717

Beginning at: 2018-07-31 18:20:31.037139

Beginning at: 2018-07-31 18:21:44.309141
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:22:22.358014

Beginning at: 2018-07-31 18:22:32.761566
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:22:50.712759

Beginning at: 2018-07-31 18:24:20.827096

Beginning at: 2018-07-31 18:24:32.358715

Beginning at: 2018-07-31 18:26:18.260515

Beginning at: 2018-07-31 18:27:11.980997

Beginning at: 2018-07-31 18:28:33.888508

Beginning at: 2018-07-31 18:29:13.056829

Beginning at: 2018-07-31 15:33:00.545909

Beginning at: 2018-07-31 15:35:22.187846
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.
192.168.80.1 [31/Jul/2018:15:35:33 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
192.168.80.1 [31/Jul/2018:15:35:34 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"

Beginning at: 2018-07-31 18:43:56.663360

Beginning at: 2018-07-31 18:44:06.517647

Beginning at: 2018-07-31 18:44:07.923519

Beginning at: 2018-07-31 18:44:09.490923

Beginning at: 2018-07-31 18:44:19.773439
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:48:33.653023

Beginning at: 2018-07-31 18:48:51.743468

Beginning at: 2018-07-31 18:49:21.722762

Beginning at: 2018-07-31 18:49:27.775250

Beginning at: 2018-07-31 18:49:32.231840

Beginning at: 2018-07-31 18:49:44.014329
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 18:52:07.770864

Beginning at: 2018-07-31 18:52:26.578788

Beginning at: 2018-07-31 18:52:59.025910

Beginning at: 2018-07-31 18:55:22.093087

Beginning at: 2018-07-31 18:55:29.657622
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.

Server shutting down.

Beginning at: 2018-07-31 15:57:51.286896
Serving on ('0.0.0.0', 5000). Hit CTRL-C to stop.
192.168.80.1 [31/Jul/2018:16:01:45 +0000] "GET / HTTP/1.1" 500 231 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.75 Safari/537.36"
